apiVersion: v1
kind: ConfigMap
metadata:
  name: user-center-cm
data:
  serverPort: "8090"
  jpaShowSql: false
  dbUserName: "duwei"
  dbPassWord: "duwei"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-center
spec:
  selector:
    matchLabels:
      app: userCenter
  replicas: 1 
  template:
    metadata:
      labels:
        app: userCenter
    spec:
      containers:
      - name: user-center
        image: duweiduwais/usercenter:v1.0.0
        command: [ "/bin/sh", "-c", "env" ]
        env:
        # 定义环境变量
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: user-center-cm
              key:serverPort
        - name: JPA_SHOW_SQL
          valueFrom:
            configMapKeyRef:
              name: user-center-cm
              key:jpaShowSql
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: user-center-cm
              key:dbUserName
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: user-center-cm
              key:dbPassWord
         restartPolicy: Never 
        

