apiVersion: v1
kind: ConfigMap
metadata:
  name: user-center-cm
data:
  SERVER_PORT: "8090"
  DB_DRIVER_CLASS_NAME: "org.h2.Driver"
  DB_URL: "jdbc:h2:mem:usercenter"
  DB_PLATFORM: "org.hibernate.dialect.H2Dialect"
  JPA_SHOW_SQL: false
  H2_CONSOLE_ENABLED: true
  DB_USERNAME: "duwei"
  DB_PASSWORD: "duwei"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-center
spec:
  selector:
    matchLabels:
      app: userCenter
  replicas: 1 
  template:
    metadata:
      labels:
        app: userCenter
    spec:
      containers:
      - name: user-center
        image: duweiduwais/usercenter:v1.0.0
        envFrom:
        - configMapRef:
          name: user-center-cm
          optional: false
        

